### ISSUE TITLE
Default to authorization_header creds location

### ISSUE THREAD

**Issue by guicassolato** [3scale-labs/authorino#71]
Since the auth credentials config was introduced (#58), users lost the default of client credentials being supplied in the `Authorization` header of the HTTP request (actually the only option possible until then). Now users MUST specify the location (and key_selector) where in the request credentials are expected to be supplied, for each identity verification config.

This is a request for the auth credentials, whenever omitted on the identity config, to default to the following values:

```yaml
credentials:
  in: authorization_header
  key_selector: Bearer
```
