### ISSUE TITLE
OAuth2 authN (token introspection)

### ISSUE THREAD

**Issue by guicassolato** [3scale-labs/authorino#82]
This is a proposal for Authorino to implement OAuth2-based identity verification, using OAuth2 `token_introspection` endpoint ([RFC 7662](https://tools.ietf.org/html/rfc7662)).

We had something similar implemented before as option in the "metadata" phase (removed in #53). This new implementation would be an alternative in the "identity" phase, to enable working work with OAuth2 servers that yet do not implement OIDC. Of course, those OAuth2 servers would have to expose the `token_introspection` endpoint (not all do).

A configuration would look like the following:

```yaml
identity:
  - name: some-oauth-server
    oauth2:
      token_introspection_url: https://oauth-server/introspect
      token_type_hint: access_token # optional (default: "access_token")
      credentialsRef:
        name: secret-containing-client-id-and-client-secret
```
